version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: UTC
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: find-up # Pure ESM package. Remove from ignore when ESM is supported
      versions:
        - ">=6.0.0"
    - dependency-name: execa # Pure ESM package. Remove from ignore when ESM is supported
      versions:
        - ">=6.0.0"
    - dependency-name: chalk # Pure ESM package. Remove from ignore when ESM is supported
      versions:
        - ">=5.0.0"
    - dependency-name: strip-ansi # Pure ESM package. Remove from ignore when ESM is supported
      versions:
        - ">=7.0.0"
    - dependency-name: wrap-ansi # Pure ESM package. Remove from ignore when ESM is supported
      versions:
        - ">=8.0.0"
    - dependency-name: jest
    - dependency-name: yargs
    - dependency-name: husky
      versions:
        - ">=5.0.0"
    - dependency-name: semantic-release
      versions:
        - ">=23.0.0"
    # Pure ESM package. Remove from ignore when ESM is supported
    # https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%409.0.0
    - dependency-name: inquirer 
      versions:
        - ">=9.0.0"
    # Pure ESM package. Remove from ignore when ESM is supported
    # https://github.com/sindresorhus/p-queue/releases/tag/v7.0.0
    - dependency-name: p-queue
      versions:
        - ">=7.0.0"
    # Pure ESM package. Remove from ignore when ESM is supported
    #https://github.com/sindresorhus/open/releases/tag/v9.0.0
    - dependency-name: open
      versions:
        - ">=9.0.0"
    commit-message:
      prefix: build
      include: scope
    groups:
      production-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'