language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm test
  - npm run build
  - ./test-e2e.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
