export default {
  needsAuthentication: [
    'boilerplate',
    'logout',
    'content-type get',
    'content-type list',
    'extension create',
    'extension delete',
    'extension get',
    'extension list',
    'extension update',
    'space create',
    'space delete',
    'space export',
    'space import',
    'space list',
    'space migration',
    'space seed',
    'space use',
    'space generate migration',
    'space accesstoken create',
    'space accesstoken list',
    'space environment create',
    'space environment delete',
    'space environment list',
    'space environment use'
  ],
  needsSpaceId: [
    'boilerplate',
    'content-type get',
    'content-type list',
    'extension create',
    'extension delete',
    'extension get',
    'extension list',
    'extension update',
    'space delete',
    'space export',
    'space import',
    'space migration',
    'space seed',
    'space use',
    'space generate migration',
    'space accesstoken create',
    'space accesstoken list',
    'space environment create',
    'space environment delete',
    'space environment list',
    'space environment use'
  ]
}
