#!/usr/bin/env node

//
// What is this?
//
// A script that takes the result of running
// `npm run build:standalone` and packages the
// resulting binaries inside files that can
// then be shared with the customers
//

const jszip = require('jszip')
const path = require('path')
const fs = require('fs')

const packageJSON = require('../package.json')

const version = packageJSON.version
const buildpath = 'build/'
const files = {
  'contentful-cli-macos': {
    to: 'contentful',
    package: 'contentful-cli-macos'
  },
  'contentful-cli-linux': {
    to: 'contentful',
    package: 'contentful-cli-linux'
  },
  'contentful-cli-win.exe': {
    to: 'contentful.exe',
    package: 'contentful-cli-win'
  }
}

console.log('Prepare zip files for each platform:\n')

Object.keys(files).forEach(async file => {
  let zip = new jszip()
  const filename = files[file].to
  const filepath = path.join(buildpath, file)
  const packageName = `${files[file].package}-${version}.zip`

  zip.file(filename, fs.readFileSync(filepath))

  const data = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE'
  })

  console.log(packageName)
  fs.writeFileSync(path.join(buildpath, packageName), data, 'binary')
})
