name: Run Checks

permissions:
  contents: read
on:
  workflow_call:
    secrets:
      CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN:
        required: false
      CLI_E2E_ORG_ID:
        required: false

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npx allow-scripts

      - name: Restore the build folders
        uses: actions/cache/restore@v4
        with:
          path: |
            dist
            build
          key: build-cache-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      # - name: Run linter
      #   run: npm run lint

      # - name: Check formatting
      #   run: npm run prettier:check

      - name: Run unit tests
        run: npm test
        env:
          CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN: ${{ secrets.CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN }}
          CLI_E2E_ORG_ID: ${{ secrets.CLI_E2E_ORG_ID }}

      - name: Run integration tests
        if: github.event_name == 'push' || github.event.pull_request.head.repo.fork == false
        run: npm run test:integration:ci
        env:
          CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN: ${{ secrets.CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN }}
          CLI_E2E_ORG_ID: ${{ secrets.CLI_E2E_ORG_ID }}
